version: '3.8'
services:
  vue:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: fc-front
    ports:
      - 8009:8080
    volumes:
      - /app/node_modules
      - ./client:/app
    restart: unless-stopped
    depends_on:
      - nest

  nest:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fc-back
    env_file: ./server/.env
    ports:
      - 8008:3000
    volumes:
      - /app/node_modules
      - ./server:/app
    restart: unless-stopped
    depends_on:
      - pg

  pg:
    image: postgres
    container_name: fc-db
    environment:
      POSTGRES_PASSWORD: food-calculator
      POSTGRES_USER: food-calculator
    volumes:
      - fc-data:/var/liv/postgresql/data
    restart: unless-stopped

  typeorm:
    build:
      context: ./server
      dockerfile: typeorm/Dockerfile
    volumes:
      - ./server:/app
    entrypoint: ['typeorm']

volumes:
  fc-data:
