version: '3.8'
services:
  vue:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: fc-front
    ports:
      - 8009:8080
    volumes:
      - /app/node_modules
      - ./client:/app
    restart: unless-stopped
    depends_on:
      - nest

  nest:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fc-back
    env_file: ./server/.env
    ports:
      - 8008:3000
    volumes:
      - /app/node_modules
      - ./server:/app
    restart: unless-stopped
#   mongo:
#     image: mongo:3.6.23
#     container_name: fc-db
#     environment:
#       MONGO_INITDB_ROOT_USERNAME:
#       MONGO_INITDB_ROOT_PASSWORD:
#     volumes:
#       - fc-data:/data/db
#     command: ['mongod', '--auth']
#     restart: unless-stopped

# volumes:
#   fc-data:
